### ISSUE TITLE
Enhancment // m3u list upload for remote sources

### ISSUE THREAD

**Issue by dfranje** [ffplayout/ffplayout#195]
Hello @jb-alvarado .
First of all , thanks you for all your work.

Enhancment request here.

Adding m3u list upload option for external sources. 

A lot of us using ffplayout have movie clips on remote servers, and are using iptv platform for distribution in m3u list format.

This would be a time reduction  for someone who wants to stream from external source to ffplayout. And instead of inserting one external source at a time, we can do this and import 100 clips in one click...

Thanks for your time.

**Comment by jb-alvarado** [comment]
Just to clarify:

* with external sources you mean something like this?:
    ```
    https://example.org/path/to/file_1.mp4
    https://example.org/path/to/file_2.mp4
    https://example.org/path/to/file_3.mp4
    ...
    ```
* the import should generate a specific playlist for a given date?
* the upload should happen with the web frontend?

For a first step, I could imagine to add a cli option, like: `ffplayout -i /path/to/list.m3u -d 2022-09-13`. This would be not to much work. For a second step I can think on a upload function. Because the files are remote, I have no idea how long it will take to convert the playlist, because we have to read the metadata from every file to get its duration. On cli that is not so much a problem, but maybe on frontend.

**Comment by dfranje** [comment]
hello

the m3u file structure example:
#EXTM3U
#EXTINF:0,moviename1
http://movieurl
#EXTINF:0,moviename1
http://movieurl
#EXTINF:0,moviename1
http://movieurl
#EXTINF:0,moviename1
http://movieurl
#EXTINF:0,moviename1
http://movieurl
#EXTINF:0,moviename1
http://movieurl

i was thinking on frontend.

i can supply a m3u list of movies clips 1:30h long for testing the remote import.

**Comment by jb-alvarado** [comment]
> i can supply a m3u list of movies clips 1:30h long for testing the remote import.

Thank you, for the moment is ok, maybe later. I have to see when I have time for this, the next months I'm very busy.

I will try to make it a bit more generic, so a simple text file would work to. I think in general line starting with `#` can be skipped. It should also respect absolute and relative paths. More specs about m3u are [here](https://de.wikipedia.org/wiki/M3U#Erweiterte_M3U).
