### ISSUE TITLE
How to use ffplayout paython v4 for only audio streaming.

### ISSUE THREAD

**Issue by Akbarmuvi** [ffplayout/ffplayout#274]
We have a playout system where user can schedule audio content to play. We are using nginx with python to run the ffplayout script.

What will be the actual ffmpg command we need to use for AUDIO Streaming.

**Comment by jb-alvarado** [comment]
Hello,
since [v0.17.0-beta3](https://github.com/ffplayout/ffplayout/releases) ffplayout has a experimental audio only mode. So there is no need, for the old python version.

For streaming setting you could observe the [ffmpeg streaming guid](http://trac.ffmpeg.org/wiki/StreamingGuide), it contains also infos about audio only.
