### ISSUE TITLE
ffplayout built-in player has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#354]
**Describe the bug**

ffplayout's built-in player is blocked by web browsers (chrome, firefox, edge) when a domain name (DNS name) is associated with the IP address where ffplayout is installed.

**To Reproduce**

Assign a domain name to the IP of the server where ffplayout is installed.

**Desktop/Server/Software (please complete the following information):**

OS: Ubuntu 22.04 server
ffplayout 18.4
ffmpeg 4.4.2-0ubuntu0.22.04.1
are you using the current master of ffplayout? No.

**Config Settings:**
Default settings

- command line arguments
Default arguments

**Web Browser Logging:**

Access to XMLHttpRequest at 'http://10.145.123.117:8787/live/stream.m3u8' from origin 'http://bntv.space:8787' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
media.43657656.js:10     GET http://10.145.123.117:8787/live/stream.m3u8 net::ERR_FAILED 200 (OK)

media.43657656.js:34 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. Re {code: 4, message: 'The media could not be loaded, either because the …rk failed or because the format is not supported.'}

![image](https://github.com/ffplayout/ffplayout/assets/8952225/4124d274-bc1f-4e1e-bcfc-0818490f7ad9)

**Comment by jb-alvarado** [comment]
Let's discuss this in the other issue.

**Comment by JunioCalu** [comment]
If I change the player_url value from "http://10.145.123.117:8787/live/stream.m3u8 " to http://bntv.space:8787/live/stream.m3u8, the problem is solved. The real problem is that without setting the Access-Control-Allow-Origin header, the browser cannot recognize that 10.145.123.117 and bntv.space is the same host with different "names", so the browser expects that the view stream source address must be the same address that loaded the ffplayout page to avoid "security" problem.

**Comment by jb-alvarado** [comment]
Sorry @JunioCalu, I will not integrate this, because to me this is more a workaround then a real solution. I don't think there is any way to dynamically update a cors setting from ffpapi. And when it goes to production and people wants to use a proxy (which is still the recommend way), it can leads to confusion and multiple cors settings on different places.

When you use ffplayout only locally, you can use IP or DNS from your local network. When you use ffplayout public setup a proxy for ssl termination and serving of hls playlists. I don't see any need mixing IP and DNS, but if you need it, use a proxy and setup there your cors rule.

**Comment by JunioCalu** [comment]
Good decision. I think maybe it would be useful when the IP of a server has more than one domain name. The example screen was implemented by datarhei/restreamer, in this case they implemented another menu to identify multiple domain names for the same server.

And by the way ffplayout and datarhei/restreamer make a good combination.
