### ISSUE TITLE
Playout system settings are not automatically applied after changes

### ISSUE THREAD

**Issue by JunioCalu** [ffplayout/ffplayout#362]
**Describe the bug**

"**Playout Configuration**" page settings are not automatically applied after changes.

**To Reproduce**

1. Go to 'http://localhost:8787/configure'.
2. Make a configuration change.
3. Click on Save .

**Expected behavior**

Immediate application of configuration changes.

**Desktop/Server/Software (please complete the following information):**

 - OS: Ubuntu server 22.04
- ffplayout 0.19.0
- ffmpeg version: 4.4.2-0ubuntu0.22.04.1 
- are you using the current master of ffplayout? No.

**Comment by jb-alvarado** [comment]
Do you mean any value on the **Channel Configuration** page? Could you make screenshot of the error?

And by the way, I see you have and older ffmpeg version, would you be so kind and send me the output from:

```
ffmpeg -h full | grep "readrate"
```

This is not related to the issue, I only want to now if this parameter exists in older versions, because I want to use it in v0.20.

**Comment by JunioCalu** [comment]
> Do you mean any value on the **Channel Configuration** page? Could you make screenshot of the error? 

from the "**Playout Configuration**" page. No error log is shown, it seems to be something related to the implementation logic, I think ffpapi should reload the config file or restart itself when a change is made on that page.

**Comment by jb-alvarado** [comment]
Ah ok. Normally all inputs in the frontend are reactive. If something not update in the gui correctly I need to fix it.

The other thing is, that ffplayout will not restart automatically, when a change in the configuration is made. This would stop the streaming. The user have to restart the Playout on the player page. I though this way is better, because there is not that much changing and user can decide when to restart.

**Comment by jb-alvarado** [comment]
I can create a dialog, which opens and ask for restarting the engine.

**Comment by JunioCalu** [comment]
> I can create a dialog, which opens and ask for restarting the engine.

It would be a great solution.
