### ISSUE TITLE
Ability to add live radio stream 

### ISSUE THREAD

**Issue by brixxnatt** [ffplayout/ffplayout#366]
ability to add live radio stream   http://ip :port/radio.mp3

**Comment by IVEN2022** [comment]
+1

**Comment by jb-alvarado** [comment]
Hello @brixxnatt, again please see my note.

Otherwise, it will help you to familiarize yourself with [ffmpeg](https://ffmpeg.org/documentation.html). Pretty much everything that is supported there can also be used in ffplayout.

If your wish is not directly supported, you might take [icecast](https://icecast.org/) and stream to it with ffplayout.

**Comment by IVEN2022** [comment]
oh here , about this , what if we want to make a video loop in ffplayout and get an icecast stream to the audio track , dose this work , and how please , thanks

**Comment by jb-alvarado** [comment]
When ffmpeg supports icecast as input, it could work for a short time, but not for long. There is two problems:
1. a endless stream has no duration information
2. because of the fact that ffplayout can't pull faster then realtime, it can happen that it starts playing choppy.
