### ISSUE TITLE
Live time now

### ISSUE THREAD

**Issue by C0la149** [ffplayout/ffplayout#485]
Hello everyone, is it even possible to display a clock live in ffplayout? I showed an example in the screenshot.
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/f2bce32e-5f37-4672-8a2f-784f64a505a3)
I need live time. To know what time it is right now. And so that the audience also knows the time. Convenient just right. You will find out from the broadcast time what time you need to leave for work.

**Comment by JunioCalu** [comment]
adding this to the parameters should work:

`-vf "drawtext=text='%{localtime\:%H\\\\\:%M\\\\\:%S}':fontcolor=white:fontsize=40:x=w-tw-20:y=20:box=1:boxcolor=red@0.7:boxborderw=10"`

to take a test:

`ffmpeg -re -i input.mp4 -vf "drawtext=text='%{localtime\:%Y-%m-%d %H\\\\\:%M\\\\\:%S}':fontcolor=white:fontsize=40:x=w-tw-20:y=20:box=1:boxcolor=green@0.7:boxborderw=10" -f mpegts udp://127.0.0.1:1234`

Another option also containing the date:

`ffmpeg -re -i input.mp4 -vf "drawtext=text='%{localtime\:%Y-%m-%d %H\\\\\:%M\\\\\:%S}':fontcolor=white:fontsize=40:x=w-tw-20:y=20:box=1:boxcolor=red@0.7:boxborderw=10" -f mpegts udp://127.0.0.1:1234`

**Comment by C0la149** [comment]
> adding this to the parameters should work:
> 
> `-vf "drawtext=text='%{localtime\:%H\\\\\:%M\\\\\:%S}':fontcolor=white:fontsize=40:x=w-tw-20:y=20:box=1:boxcolor=red@0.7:boxborderw=10"`
> 
> to take a test:
> 
> `ffmpeg -re -i rabinorelogio.mp4 -vf "drawtext=text='%{localtime\:%H\\\\\:%M\\\\\:%S}':fontcolor=white:fontsize=40:x=w-tw-20:y=20:box=1:boxcolor=red@0.7:boxborderw=10" -f mpegts udp://127.0.0.1:1234`
> 
> `mpv "udp://127.0.0.1:1234"`
> 
> Another option also containing the date:
> 
> `ffmpeg -re -i input.mp4 -vf "drawtext=text='%{localtime\:%Y-%m-%d %H\\\\\:%M\\\\\:%S}':fontcolor=white:fontsize=40:x=w-tw-20:y=20:box=1:boxcolor=red@0.7:boxborderw=10" -f mpegts udp://127.0.0.1:1234`

Where should I write all this? You can show?

**Comment by JunioCalu** [comment]
> Where should I write all this? You can show? @JunioCalu

You would have to add the initial parameters I sent in the 'output_param' configuration session. Almost all ffmpeg parameters work in ffplayout, but the parameters I suggested to you did not work when I tested them in practice just now, because the '-vf' parameter adds the system clock time through a simple filter, but I just noticed that ffplayout is using complex filters in its engine, and these filters can only be edited by changing the ffplayout source code.

Another option would be to trigger a subtitle, through the messages menu (localhost:8787/messages), but that's also not working because ffplayout is adding extra escape characters when processing the subtitle parameters configured in the web interface through the zmq function of ffmpeg.

So, if the project author @jb-alvarado doesn't have another suggestion, I think the only thing left for you is to edit the source code to add the system clock to the live stream.

**Comment by jb-alvarado** [comment]
Normally you can use any filter in filter_complex. It should work in output, but also in `custom_filter`.

**Comment by JunioCalu** [comment]
Works fine!

![Screenshot_20240114_181106](https://github.com/ffplayout/ffplayout/assets/8952225/8593223e-cc45-4d67-bae4-1c8de6eb03ff)

**Comment by C0la149** [comment]
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/0024cb6c-a601-449c-85bf-edc294f5c667)
![изображение](https://github.com/ffplayout/ffplayout/assets/64633686/af76335a-54ef-4a0c-8b6c-01e3ac981d12)

Yes, it works!
Thank you!
Now I’m going to think about how to move the clock and make it a little smaller)
Thanks for the help!
@jb-alvarado
