### ISSUE TITLE
Uninstall and Update.

### ISSUE THREAD

**Issue by LuizStSantos** [ffplayout/ffplayout#539]
Could you make a guide to uninstall, and one to update to a new version, or even add a button to the web UI that searches for updates and updates them?

**Comment by jb-alvarado** [comment]
Uninstalling is the same then all other normal packages. On a debian based system you can run `apt remove ffplayout` or `apt purge ffplayout`. Updating is the same, you just install the new version, like `apt install /tmp/ffplayout-v0.20.4-1_x86-64.deb`. You can also use `reinstall` instead of install, to install same version again, or using `--allow-downgrades` to downgrade to an older version.
