### ISSUE TITLE
Cant Add video that belongs to diffrent Owner or Group .

### ISSUE THREAD

**Issue by brixxnatt** [ffplayout/ffplayout#657]
Cant Add video to the playlist that belongs to diffrent Owner or Group .
please how to fix this IMPORTANT

**Comment by LuizStSantos** [comment]
```
How to Change Directory Permissions in Linux for the Group Owners and Others
The command for changing directory permissions for group owners is similar, but add a “g” for group or “o” for users:

chmod g+w filename

chmod g-wx filename

chmod o+w filename

chmod o-rwx foldername
``` 

[HOW TO GIVE PERMISSIONS](https://www.pluralsight.com/blog/it-ops/linux-file-permissions)

**Comment by JunioCalu** [comment]
The ffplayout execution process is managed as a systemd service (daemon), and systemd seems to be linked to this issue of restricted access to specific folders, I believe. If you try to create a "video" folder for storing media files, and this videos folder is located within a common user's home directory such as /home/youruser/video/clips, and then correctly and recursively set the access permissions for this "video" folder to ffpu as the owner and ffpu as the group, and subsequently designate this folder as the default media storage folder in the ffplayout settings, ffplayout will simply return an access permissions error and will be unable to access it. Interestingly, if the media storage folders are placed within the "/var" or "/home/ffpu/" directory with the proper file permissions set, they will be accessible by ffplayout. Therefore, even if you set the correct file permissions, there may still be access restrictions depending on the path of the media storage folder you wish to work with.

**Comment by brixxnatt** [comment]
The Problem is that the videos is from another streaming  platfrom, and i need to play always those files that is recorded in a folder , I need a way to make ffplayout read and play the root mp4 files what belongs for example to www-data or root

**Comment by jb-alvarado** [comment]
When the permission is 644 reading and playing is not a problem. Only when you need to write it become one. Then the folder needs 777 or you let ffplayout run as different user, for example as www-data. Changing the user I would not recommend for everyone, because then you have to change all permissions, for config, log, sudo, etc. and maybe it makes updates difficult.

**Comment by brixxnatt** [comment]
the files is chmodded 755 in the folder and belongs to www-data , how can i make this possible with ffplaout , what is the instruction i can use to make them usable
thank a lot for all the help

**Comment by jb-alvarado** [comment]
Is difficult to say, what the problem is. Are the files listed in frontend? I use all the time different file owners, but I don't use ffplayout for file upload, only for playing.

You could observe system logs and see where is the problem is. You can also create a folder directly in root like "/tv-media" and add all your files there and the folder you give 777. 755 for files is not needed, that means you give them a execution bit, normally you don't want this. Only folders and binaries/scripts needs a execution bit.

**Comment by brixxnatt** [comment]
yes i can see them in the front end  , but cant add them to playlist
