### ISSUE TITLE
Failed connection attempts on rtmp ingest stops folder playback

### ISSUE THREAD

**Issue by cakebread** [ffplayout/ffplayout#848]
Two to five times a day, playback from folder is interrupted by connection attempts on the ingest server. These connections aren't by me. I've changed the stream key a few times, but it still occurs. When the connection occurs, folder playback is stopped then restarted.

I realize I can use a firewall to whitelist IPs that can connect to that port, but it does affect playback, so I'm reporting it.

ffplayout version 0.21.4
Ubuntu 24.04
ffmpeg 7.0.2

Relevant log portion:

[ERROR] [Server] [rtmp @ 0x55d2417f2280] Unable to read handshake
[ERROR] [Server] Error opening input file rtmp://0.0.0.0:1936/live/<redacted>
[ERROR] [Server] Error opening input files: Input/output error
[ERROR] [Server] [rtmp @ 0x55d589580340] Erroneous Message size 87 not following standard
[ERROR] [Server] [rtmp @ 0x55d589580280] RTMP Handshake C1 Error
[ERROR] [Server] [in#0 @ 0x55d58957f8c0] Error opening input: Invalid argument
[ERROR] [Server] Error opening input file rtmp://0.0.0.0:1936/live/<redacted>
[ERROR] [Server] Error opening input files: Invalid argument
[ERROR] Encoder write error: broken pipe
[ INFO] Playout done...
[ INFO] RPC server listening on 127.0.0.1:7070
[ INFO] Playout in folder mode

**Comment by jb-alvarado** [comment]
Hello @cakebread, When your ingest is listening to the world (0.0.0.0), then the chance is high that there is some incoming noise, because of port scanners that are scanning the internet.

Anyway that noise should not affect the normal playout, but I think I remember that in older versions there was a bug that create that issue. 

I the current version this should not be happen any more. If you want to stick on that version you are using, you could use something like a rtmp proxy. A server like SRS that listen to the world, and forward real rtmp traffic to your ffplayout.
